variables:
  GITHUB_TOKEN: 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
  #$GITHUB_TOKEN
stages:
  - sync

sync_to_github:
  stage: sync
  image: alpine:latest
  before_script:
    - apk add --update git  # Install git in the alpine container
  script:
    # 1. Define the target URL with authentication
    # Replace 'username/repository.git' with your actual GitHub path
    - GITHUB_URL="https://x-access-token:${GITHUB_TOKEN}@github.com/icis4/gitlab_copy.git"
    
    # 2. Add the GitHub remote
    - git remote add github $GITHUB_URL
    
    # 3. Push the current branch to GitHub
    # Using --force ensures the mirrors match, but use with caution
    - git push github HEAD:refs/heads/$CI_COMMIT_REF_NAME --force
  only:
    - main  # Only run this when the main branch is updated
